apiVersion: v1
kind: PersistentVolume
metadata:
  name: cfme-pv01
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  nfs: 
    path: /exports/cfme-pv01
    server: support1.rdu12.internal
  persistentVolumeReclaimPolicy: Retain
