apiVersion: v1
kind: PersistentVolume
metadata:
  name: cfme-pv03
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs: 
    path: /exports/cfme-pv03
    server: support1.rdu12.internal
  persistentVolumeReclaimPolicy: Retain
